"""
Django settings for paper_analyzer_app project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv, find_dotenv
import mimetypes


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

mimetypes.add_type("text/css", ".css", True)

load_dotenv(find_dotenv())
# ^ env vars are passed into container directly so this only \
# has an effect when running locally

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Check if running locally
RUNNING_LOCALLY = os.getenv('RUNNING_LOCALLY') == 'true'
REDIS_PORT = int(os.getenv('REDIS_PORT', '6379'))

# Database configuration
if RUNNING_LOCALLY:
    DB_HOST = 'localhost'
    REDIS_HOST = 'localhost'
    if os.getenv("CELERY_FORCE_ASYNC") == 'true':
        CELERY_TASK_ALWAYS_EAGER = False
        CELERY_TASK_EAGER_PROPAGATES = False
    else:
        CELERY_TASK_ALWAYS_EAGER = True
        CELERY_TASK_EAGER_PROPAGATES = True
else:
    DB_HOST = os.getenv('DB_HOST')
    REDIS_HOST = os.getenv('REDIS_HOST')
    CELERY_TASK_ALWAYS_EAGER = False
    CELERY_TASK_EAGER_PROPAGATES = False

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise Exception("DJANGO_SECRET_KEY environment variable not set!")
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',
    'django_extensions',
    'rest_framework',
    'channels',
    'storages',
    'vso_query_builder',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "paper_analyzer_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "paper_analyzer_app.wsgi.application"
ASGI_APPLICATION = 'paper_analyzer_app.asgi.application'


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/1',  # Use database 1 for caching
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': DB_HOST,
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Media files
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# S3 Storage (production)
USE_S3 = os.getenv('USE_S3', 'false').lower() == 'true'

if USE_S3:
    STORAGES = {
        "default": {
            # Custom backend: uses IAM role, ignoring AWS env vars (which are for Bedrock)
            "BACKEND": "paper_analyzer_app.storage_backends.IAMRoleS3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_QUERYSTRING_EXPIRE = 3600  # presigned URL expiry (1 hour)
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None

# Celery settings
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'

# Route the hang-prone CPU/subprocess/network tasks to a dedicated `cpu` queue
# served by a PREFORK worker (process isolation + hard timeouts). Everything else
# stays on the default `celery` queue (the gevent worker). See docker-compose
# `celery-cpu` and the per-task soft/hard time_limits on these two tasks.
CELERY_TASK_ROUTES = {
    'vso_query_builder.tasks.extract_paper_text_task': {'queue': 'cpu'},
    'vso_query_builder.tasks.analyze_dataset_usage': {'queue': 'cpu'},
    # Commit replays run on prefork too: per-task process isolation avoids the
    # gevent worker's shared-connection churn (@close_db_connection mid-loop).
    'vso_query_builder.tasks.commit_chunk_task': {'queue': 'cpu'},
    # Bulk embedding sweep (network + DB batch work, off the commit hot path).
    'vso_query_builder.tasks.embed_missing_quotes': {'queue': 'cpu'},
    # Bulk PDF-coordinate enrichment: one PDF-parse per paper, CPU-bound, off the
    # commit hot path. Per-task time_limit isolates a pathological PDF to one proc.
    'vso_query_builder.tasks.enrich_quote_coordinates': {'queue': 'cpu'},
    # Batch-result ingest parses a whole job's S3 output in memory (each record
    # echoes its ~70KB input). On the long-lived gevent worker this stacked onto
    # retained heap and OOM-killed it 3x during cohort_10k (silent task loss,
    # multi-hour pipeline stalls); prefork children recycle memory per task.
    'vso_query_builder.tasks.ingest_batch_results': {'queue': 'cpu'},
    # Phenomena enrichment: LLM + PDF work, intentional-only, per-paper.
    'vso_query_builder.tasks.run_phenomena_enrichment': {'queue': 'cpu'},

    # --- corpus-scale queue topology (DESIGN_1M_SCALE.md §3) ---
    # `control` — the small, latency-critical driver tasks. Consumed by the
    # gevent worker alongside the default queue (-Q celery,control), but as a
    # NAMED queue it can never be buried behind bulk work, its depth is
    # independently observable/alarmable, and a corpus box can give it a
    # dedicated worker with zero code change.
    'vso_query_builder.tasks.advance_run_task': {'queue': 'control'},
    'vso_query_builder.tasks.advance_pipeline_task': {'queue': 'control'},
    'vso_query_builder.tasks.reconcile_batch_downstream_runs': {'queue': 'control'},
    'vso_query_builder.tasks.pipeline_stage_done': {'queue': 'control'},
    # `replay` — CPU-bound, DB-only collection chunks. Prefork (consumed by the
    # cpu worker via -Q cpu,replay); the corpus box scales this fleet to 32-64
    # procs, which is the whole replay-tax story at 1M papers.
    'vso_query_builder.tasks.collect_chunk_task': {'queue': 'replay'},
}

# Celery settings for development

# Github
PAPER_DATA_LINKS_GITHUB_ACCESS_TOKEN = os.getenv('PAPER_DATA_LINKS_GITHUB_ACCESS_TOKEN')
PAPER_DATA_LINKS_GITHUB_REPO = os.getenv('PAPER_DATA_LINKS_GITHUB_REPO')
BASE_URL = os.getenv("BASE_URL")

ADS_API_KEY = os.getenv("ADS_TOKEN")
