# Generated by Django 5.0.2 on 2024-02-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="papers/%Y/%m/%d/"),
        ),
    ]
