# Generated by Django 5.0.2 on 2024-02-21 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0006_alter_critique_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="critique",
            name="user",
        ),
    ]
