# Generated by Django 5.0.2 on 2024-03-14 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0012_critique_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="critique",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
