# Generated by Django 5.0.2 on 2024-05-14 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0015_prediction_pushed_to_github"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paper",
            old_name="doi",
            new_name="bibcode",
        ),
    ]
