# Generated by Django 5.0.8 on 2025-01-17 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0017_prediction_annotated_pdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_valid_python", models.BooleanField(default=False)),
                ("has_syntax_errors", models.BooleanField(default=False)),
                ("execution_successful", models.BooleanField(default=False)),
                ("execution_error", models.TextField(blank=True, null=True)),
                ("instruments_found", models.JSONField(default=list)),
                ("wavelengths_found", models.JSONField(default=list)),
                ("time_ranges", models.JSONField(default=list)),
                ("has_results", models.BooleanField(default=False)),
                ("result_count", models.IntegerField(default=0)),
                ("text_coverage_score", models.FloatField(default=0.0)),
                ("metrics", models.JSONField(default=dict)),
                (
                    "prediction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="vso_query_builder.prediction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prediction Analysis",
                "verbose_name_plural": "Prediction Analyses",
            },
        ),
        migrations.CreateModel(
            name="PredictionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("batch_stats", models.JSONField(blank=True, null=True)),
                (
                    "predictions",
                    models.ManyToManyField(
                        related_name="batch", to="vso_query_builder.prediction"
                    ),
                ),
                (
                    "predictor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="vso_query_builder.predictor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prediction_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
