# Generated by Django 5.0.8 on 2025-01-17 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0018_predictionanalysis_predictionbatch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionbatch",
            name="description",
        ),
        migrations.RemoveField(
            model_name="predictionbatch",
            name="name",
        ),
    ]
