# Generated by Django 5.0.8 on 2025-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0019_remove_predictionbatch_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionanalysis",
            name="has_syntax_errors",
        ),
        migrations.RemoveField(
            model_name="predictionanalysis",
            name="metrics",
        ),
        migrations.RemoveField(
            model_name="predictionanalysis",
            name="result_count",
        ),
        migrations.RemoveField(
            model_name="predictionanalysis",
            name="text_coverage_score",
        ),
        migrations.RemoveField(
            model_name="predictionanalysis",
            name="wavelengths_found",
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="analyzer_outputs",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="is_safe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="search_calls",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="security_issues",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="syntax_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="wavelengths",
            field=models.JSONField(default=list),
        ),
    ]
