# Generated by Django 5.0.8 on 2025-01-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0021_remove_predictionanalysis_has_results_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionanalysis",
            name="no_vso_sources",
            field=models.BooleanField(
                default=False, help_text="True if no VSO data sources were found"
            ),
        ),
    ]
