# Generated by Django 5.0.8 on 2025-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0022_predictionanalysis_no_vso_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="used_ocr",
            field=models.BooleanField(default=False),
        ),
    ]
