# Generated by Django 5.0.8 on 2025-01-30 16:33

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0023_paper_used_ocr"),
    ]

    operations = [
        VectorExtension()
    ]
