# Generated by Django 5.0.8 on 2025-01-30 18:11

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import vso_query_builder.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0024_auto_20250130_1633"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.JSONField()),
                ("instruments_details", models.TextField()),
                (
                    "annotated_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=vso_query_builder.models.annotated_pdf_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vso_query_builder.paper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper Analysis",
                "verbose_name_plural": "Paper Analyses",
            },
        ),
        migrations.CreateModel(
            name="SupportQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("instrument", models.CharField(max_length=100)),
                ("parameter", models.CharField(max_length=100)),
                ("page_number", models.IntegerField()),
                ("y_coord", models.FloatField()),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=1536, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_quotes",
                        to="vso_query_builder.paperanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Quote",
                "verbose_name_plural": "Support Quotes",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="support_quote_embedding_idx",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
