# Generated by Django 5.0.8 on 2025-01-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0025_paperanalysis_supportquote"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperanalysis",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
