# Generated by Django 5.0.8 on 2025-02-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0026_paperanalysis_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperanalysis",
            name="token_usage",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
