# Generated by Django 5.0.8 on 2025-02-07 18:48

from django.db import migrations, transaction


def move_prediction_data(apps, schema_editor):
    Prediction = apps.get_model('vso_query_builder', 'Prediction')
    PaperAnalysis = apps.get_model('vso_query_builder', 'PaperAnalysis')
    SupportQuote = apps.get_model('vso_query_builder', 'SupportQuote')

    # Get predictions for papers without analysis, but with metadata
    predictions = Prediction.objects.filter(
        paper__paperanalysis__isnull=True,
        metadata__has_key='support_quotes'
    ).select_related('paper').distinct('paper')  # One prediction per paper

    print(f"Found {predictions.count()} papers to migrate")

    for prediction in predictions:
        try:
            with transaction.atomic():
                analysis = PaperAnalysis.objects.get_or_create(
                    paper=prediction.paper,
                    defaults={
                        'context': prediction.context or [],
                        'instruments_details': prediction.metadata.get('instruments_details', ''),
                        'annotated_pdf': prediction.annotated_pdf,
                        'status': 'completed',
                        'token_usage': prediction.metadata.get('token_usage')
                    }
                )[0]

                quotes = prediction.metadata.get('support_quotes', [])
                support_quotes = []
                for quote in quotes:
                    SupportQuote.objects.get_or_create(
                        paper_analysis=analysis,
                        quote=quote['quote'],
                        instrument=quote['instrument'],
                        parameter=quote['parameter'],
                        defaults={
                            'page_number': quote.get('page_number', 0),
                            'y_coord': quote.get('y_coord', 0.0)
                        }
                    )
                print(f"Migrated paper {prediction.paper.bibcode} with {len(quotes)} quotes")

        except Exception as e:
            print(f"Failed to migrate paper {prediction.paper.bibcode}: {str(e)}")


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0027_paperanalysis_token_usage"),
    ]

    operations = [
        migrations.RunPython(
            move_prediction_data,
            migrations.RunPython.noop
        )
    ]
