# Generated by Django 5.0.8 on 2025-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0028_auto_20250207_1848"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
