# Generated by Django 5.0.8 on 2025-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0029_paper_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportquote",
            name="x_coord_end",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="supportquote",
            name="x_coord_start",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="supportquote",
            name="y_coord_end",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="supportquote",
            name="y_coord_start",
            field=models.FloatField(default=0.0),
        ),
    ]
