# Generated by Django 5.0.8 on 2025-03-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vso_query_builder",
            "0030_supportquote_x_coord_end_supportquote_x_coord_start_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionanalysis",
            name="search_calls_summary",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="successful_search_calls",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="total_search_calls",
            field=models.IntegerField(default=0),
        ),
    ]
