# Generated by Django 5.0.8 on 2025-03-12 17:33
from django.db import migrations


def update_no_vso_sources_flag(apps, schema_editor):
    """Update the no_vso_sources flag for all existing prediction analyses"""
    # Get the models from the app registry
    Prediction = apps.get_model('vso_query_builder', 'Prediction')
    PredictionAnalysis = apps.get_model('vso_query_builder', 'PredictionAnalysis')

    # We had this value hardcoded into our process at this point, but afterwards we move to using a constant.
    NO_VSO_SOURCES_FLAG = "No VSO data sources found."

    # Find all predictions with script_no_commentary that exactly matches the flag
    matching_predictions = Prediction.objects.filter(
        script_no_commentary=NO_VSO_SOURCES_FLAG
    )

    # Find and update all existing analyses for these predictions
    existing_analyses = PredictionAnalysis.objects.filter(
        prediction__in=matching_predictions,
        no_vso_sources=False  # Only the ones where the flag is not set yet
    )

    # Count records that will be updated
    to_update_count = existing_analyses.count()

    # Update existing analyses where flag is False
    existing_analyses.update(no_vso_sources=True)

    # Log the counts
    print(f"Updated {to_update_count} existing analyses")


def reverse_migration(apps, schema_editor):
    """No need to reverse this data migration"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0031_predictionanalysis_search_calls_summary_and_more"),
    ]

    operations = [
        migrations.RunPython(update_no_vso_sources_flag, reverse_migration),
    ]
