# Generated by Django 5.0.8 on 2025-03-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0032_update_no_vso_sources_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionanalysis",
            name="real_execution_error_traceback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="predictionanalysis",
            name="real_execution_error_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
