# Generated by Django 5.0.8 on 2025-03-13 15:20

from django.db import migrations

# Define the standardized flag constant
NO_VSO_SOURCES_FLAG = "NO_VSO_SOURCES"

# Define possible variations of "no VSO sources" messages
# that might exist in current data
POSSIBLE_NO_VSO_MESSAGES = [
    "No VSO data sources found."
]


def update_no_vso_flags(apps, schema_editor):
    """
    1. Find all predictions with "No VSO sources" messages and standardize their fields
    2. Update all corresponding analyses (where they exist) to have no_vso_sources=True
    """
    # Get the models from the app registry
    PredictionAnalysis = apps.get_model("vso_query_builder", 'PredictionAnalysis')
    Prediction = apps.get_model("vso_query_builder", 'Prediction')

    # STEP 1: Find all predictions with script_no_commentary containing any of the no VSO messages
    updated_predictions = []
    update_count = 0

    for message in POSSIBLE_NO_VSO_MESSAGES:
        # Find all predictions with this message
        predictions = Prediction.objects.filter(script_no_commentary__contains=message)
        print(f"Found {predictions.count()} predictions with message: '{message}'")

        for prediction in predictions:
            # Skip if already using the correct flag
            if prediction.script_no_commentary == NO_VSO_SOURCES_FLAG:
                continue

            # Update the prediction fields
            prediction.script = NO_VSO_SOURCES_FLAG
            prediction.script_no_commentary = NO_VSO_SOURCES_FLAG
            prediction.rationale = NO_VSO_SOURCES_FLAG
            prediction.save(update_fields=['script', 'script_no_commentary', 'rationale'])

            # Keep track of updated predictions
            updated_predictions.append(prediction.id)
            update_count += 1

    print(f"Updated {update_count} predictions with standardized no VSO sources flag")

    # STEP 2: Update all analyses for predictions that now have the flag
    analyses_update_count = 0

    # Find all predictions that now have the standardized flag
    flag_predictions = Prediction.objects.filter(script_no_commentary=NO_VSO_SOURCES_FLAG)
    print(f"Found {flag_predictions.count()} predictions with standardized flag")

    # Get their IDs
    prediction_ids_with_flag = set(flag_predictions.values_list('id', flat=True))

    # Find all existing analyses for these predictions
    analyses = PredictionAnalysis.objects.filter(prediction_id__in=prediction_ids_with_flag)
    print(f"Found {analyses.count()} existing analyses for predictions with the flag")

    # Update the analyses that don't already have no_vso_sources=True
    analyses_to_update = analyses.filter(no_vso_sources=False)

    for analysis in analyses_to_update:
        analysis.no_vso_sources = True
        analysis.save(update_fields=['no_vso_sources'])
        analyses_update_count += 1

    print(f"Updated {analyses_update_count} analyses to have no_vso_sources=True")

    # Additional check for consistency
    total_flag_predictions = Prediction.objects.filter(script_no_commentary=NO_VSO_SOURCES_FLAG).count()
    total_flag_analyses = PredictionAnalysis.objects.filter(no_vso_sources=True).count()
    print(
        f"After migration: {total_flag_predictions} predictions have the flag, {total_flag_analyses} analyses have no_vso_sources=True")


def reverse_update_no_vso_flags(apps, schema_editor):
    """
    This is a no-op since we don't want to reverse this data migration
    We don't know what the original values were.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "vso_query_builder",
            "0033_predictionanalysis_real_execution_error_traceback_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(update_no_vso_flags, reverse_update_no_vso_flags),
    ]