# Generated by Django 5.0.8 on 2025-03-26 17:39

import re
from django.db import migrations
from django.conf import settings
from github import Github


def sanitize(name):
    """
    Sanitize a name for use in a branch name - copied from model method
    """
    name = re.sub(r'[^a-zA-Z0-9-]', '_', name)
    if not name or (not name[0].isalpha() and name[0] != '_'):
        name = '_' + name
    return name


def generate_github_branch_name(prediction, paper_bibcode, predictor_name):
    """
    Standalone implementation of the branch name logic
    """
    return f"script--{sanitize(paper_bibcode)}--{sanitize(predictor_name)}--{prediction.id}"


def find_pr_for_prediction(prediction, paper_bibcode, predictor_name, github_client, repo):
    """
    Find the PR URL for a prediction that was previously pushed to GitHub
    """
    try:
        branch_name = generate_github_branch_name(prediction, paper_bibcode, predictor_name)

        # Look for PRs with this branch name
        for state in ['open', 'closed']:
            prs = repo.get_pulls(state=state)
            for pr in prs:
                if pr.head.ref == branch_name:
                    return pr.html_url
    except Exception as e:
        print(f"Error finding PR for prediction {prediction.id}: {str(e)}")

    return None


def backfill_github_pr_urls(apps, schema_editor):
    """
    Find and fill in github_pr_url for all predictions where pushed_to_github=True
    but github_pr_url is None
    """
    # Get the models
    Prediction = apps.get_model('vso_query_builder', 'Prediction')
    Paper = apps.get_model('vso_query_builder', 'Paper')
    Predictor = apps.get_model('vso_query_builder', 'Predictor')

    # Get settings
    github_token = getattr(settings, 'PAPER_DATA_LINKS_GITHUB_ACCESS_TOKEN', None)
    repo_name = getattr(settings, 'PAPER_DATA_LINKS_GITHUB_REPO', None)

    if not github_token or not repo_name:
        print("Missing GitHub token or repo name in settings. Skipping PR URL backfill.")
        return

    # Initialize GitHub API
    github_client = Github(github_token)
    repo = github_client.get_repo(repo_name)

    # Find all predictions that have been pushed to GitHub but don't have a PR URL
    predictions = Prediction.objects.filter(pushed_to_github=True, github_pr_url__isnull=True)
    print(f"Found {predictions.count()} predictions without PR URLs.")

    # Update each prediction
    updated_count = 0
    for prediction in predictions:
        # Get the paper and predictor for this prediction
        paper = Paper.objects.get(id=prediction.paper_id)
        predictor = Predictor.objects.get(id=prediction.predictor_id)

        # Find the PR
        pr_url = find_pr_for_prediction(prediction, paper.bibcode, predictor.name, github_client, repo)
        if pr_url:
            prediction.github_pr_url = pr_url
            prediction.save()
            updated_count += 1
            print(f"Updated prediction {prediction.id} with PR URL: {pr_url}")
        else:
            print(f"Could not find PR URL for prediction {prediction.id}")

    print(f"Migration complete. Updated {updated_count} predictions with PR URLs.")


def reverse_migration(apps, schema_editor):
    """
    No-op for reverse migration
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0035_prediction_github_pr_url"),
    ]

    operations = [
        migrations.RunPython(backfill_github_pr_urls, reverse_migration),
    ]
