# Generated by Django 5.0.8 on 2025-05-07 18:57

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vso_query_builder", "0036_backfill_github_pr_urls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Observatory",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_name", models.CharField(max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                (
                    "datasource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vso_query_builder.datasource",
                    ),
                ),
                (
                    "observatory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vso_query_builder.observatory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatasetUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "observation_window",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("extra_params", models.JSONField(blank=True, default=dict)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_usages",
                        to="vso_query_builder.paper",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_usages",
                        to="vso_query_builder.prediction",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vso_query_builder.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CanonicalDatasetUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "observation_window",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("extra_params", models.JSONField(blank=True, default=dict)),
                ("validated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_usages",
                        to="vso_query_builder.paper",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raw_sources",
                    models.ManyToManyField(
                        related_name="+", to="vso_query_builder.datasetusage"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vso_query_builder.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstrumentSourceLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["instrument"], name="vso_query_b_instrum_e46f1a_idx"
                    )
                ],
                "unique_together": {("instrument", "source")},
            },
        ),
        migrations.AddIndex(
            model_name="datasetusage",
            index=models.Index(
                fields=["instrument"], name="vso_query_b_instrum_9a4e68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasetusage",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["observation_window"], name="vso_query_b_observa_c23c7e_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="canonicaldatasetusage",
            index=models.Index(
                fields=["instrument"], name="vso_query_b_instrum_6a9f37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="canonicaldatasetusage",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["observation_window"], name="vso_query_b_observa_595df5_gist"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="canonicaldatasetusage",
            unique_together={("paper", "instrument", "observation_window")},
        ),
        migrations.AlterUniqueTogether(
            name="instrument",
            unique_together={("observatory", "short_name")},
        ),
    ]
