# Generated by Django 5.2.1 on 2025-06-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0037_datasource_observatory_instrument_datasetusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperanalysis',
            name='structured_instruments_details',
            field=models.JSONField(blank=True, help_text='Structured JSON representation of instrument details from markdown', null=True),
        ),
    ]
