# Generated by Django 5.2.1 on 2025-06-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0038_paperanalysis_structured_instruments_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperanalysis',
            name='normalized_instrument_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
