# Generated by Django 5.2.1 on 2025-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0039_paperanalysis_normalized_instrument_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetusage',
            name='origin',
            field=models.CharField(choices=[('legacy_llm', 'legacy_llm'), ('normalized', 'normalized')], default='legacy_llm', help_text='Source of this usage: old LLM path vs. new normalized path', max_length=20),
        ),
    ]
