# Generated by Django 5.2.1 on 2025-06-12 14:25

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0041_alter_datasetusage_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='instrument_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
