# Generated by Django 5.2.1 on 2025-06-13 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0042_instrument_description_instrument_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedScript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('script', models.TextField(help_text='The deterministically generated Python script.')),
                ('source', models.CharField(default='deterministic', help_text='The method used for generation.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_script', to='vso_query_builder.paper')),
                ('source_usages', models.ManyToManyField(related_name='generated_scripts', to='vso_query_builder.datasetusage')),
            ],
            options={
                'verbose_name': 'Generated Script',
                'verbose_name_plural': 'Generated Scripts',
            },
        ),
    ]
