# Generated by Django 5.2.1 on 2025-06-18 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vso_query_builder", "0043_generatedscript"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetUsageAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "python_snippet",
                    models.TextField(
                        help_text="Generated Python code snippet for this dataset usage"
                    ),
                ),
                (
                    "is_valid_syntax",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the snippet has valid Python syntax",
                    ),
                ),
                (
                    "syntax_error",
                    models.TextField(
                        blank=True, help_text="Syntax error details if any"
                    ),
                ),
                (
                    "execution_successful",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the snippet executed successfully",
                    ),
                ),
                (
                    "execution_error",
                    models.TextField(
                        blank=True, help_text="Execution error details if any"
                    ),
                ),
                (
                    "total_results_found",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of results returned by query",
                        null=True,
                    ),
                ),
                (
                    "analyzer_outputs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw results from all analyzers",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_usage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="vso_query_builder.datasetusage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataset Usage Analysis",
                "verbose_name_plural": "Dataset Usage Analyses",
                "indexes": [
                    models.Index(
                        fields=["is_valid_syntax"],
                        name="vso_query_b_is_vali_ff5cd1_idx",
                    ),
                    models.Index(
                        fields=["execution_successful"],
                        name="vso_query_b_executi_7cc03f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="vso_query_b_created_4d735f_idx"
                    ),
                ],
            },
        ),
    ]
