# Generated by Django 5.2.1 on 2025-06-24 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vso_query_builder", "0045_supportquote_dataset_usages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetusage",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, help_text="When this dataset usage was validated", null=True
            ),
        ),
        migrations.AddField(
            model_name="datasetusage",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who validated this dataset usage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_dataset_usages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datasetusage",
            name="validation_notes",
            field=models.TextField(
                blank=True, help_text="Optional notes from the validator", null=True
            ),
        ),
        migrations.AddField(
            model_name="datasetusage",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("needs_review", "Needs Review"),
                ],
                default="pending",
                help_text="Validation status of this dataset usage",
                max_length=20,
            ),
        ),
    ]
