# Generated by Django 5.2.1 on 2025-06-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vso_query_builder", "0046_add_validation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportquote",
            name="coordinate_regions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Array of coordinate regions for multi-line quotes: [{"page": 1, "x0": 100, "y0": 200, "x1": 300, "y1": 210}, ...]',
            ),
        ),
    ]
