# Generated by Django 5.2.1 on 2025-06-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0047_supportquote_coordinate_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteUsageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_category', models.CharField(choices=[('instrument', 'Instrument Identification'), ('time_range', 'Time Range/Period'), ('wavelength', 'Wavelength/Energy'), ('observable', 'Physical Observable'), ('general', 'General Reference')], help_text='What aspect of the dataset usage this quote supports', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_links', to='vso_query_builder.datasetusage')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_links', to='vso_query_builder.supportquote')),
            ],
            options={
                'verbose_name': 'Quote Usage Link',
                'verbose_name_plural': 'Quote Usage Links',
                'indexes': [models.Index(fields=['support_category'], name='vso_query_b_support_5b239e_idx'), models.Index(fields=['created_at'], name='vso_query_b_created_0436b3_idx')],
                'unique_together': {('quote', 'dataset_usage', 'support_category')},
            },
        ),
    ]
