# Generated by Django 5.2.1 on 2025-07-13 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0048_quoteusagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(help_text="Type of LLM call (e.g., 'paper_analysis', 'time_normalization', 'instrument_validation')", max_length=100)),
                ('model_name', models.CharField(help_text="Full LiteLLM model string (e.g., 'openai/gpt-4o', 'anthropic/claude-3-haiku')", max_length=100)),
                ('provider', models.CharField(help_text='LLM provider extracted from model name', max_length=50)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('input_messages', models.JSONField(blank=True, help_text='The messages sent to the LLM', null=True)),
                ('output_content', models.TextField(blank=True, help_text='The response content from the LLM', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration of the API call in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional call metadata (finish_reason, kwargs, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM Call',
                'verbose_name_plural': 'LLM Calls',
                'indexes': [models.Index(fields=['call_type'], name='vso_query_b_call_ty_97693d_idx'), models.Index(fields=['model_name'], name='vso_query_b_model_n_e7b1ae_idx'), models.Index(fields=['provider'], name='vso_query_b_provide_f1f6ce_idx'), models.Index(fields=['created_at'], name='vso_query_b_created_98853d_idx'), models.Index(fields=['estimated_cost_usd'], name='vso_query_b_estimat_4460c3_idx'), models.Index(fields=['total_tokens'], name='vso_query_b_total_t_985b53_idx')],
            },
        ),
        migrations.AddField(
            model_name='datasetusage',
            name='llm_calls',
            field=models.ManyToManyField(blank=True, help_text='LLM calls associated with this dataset usage (normalization, grounding, etc.)', related_name='dataset_usages', to='vso_query_builder.llmcall'),
        ),
        migrations.AddField(
            model_name='datasetusageanalysis',
            name='llm_calls',
            field=models.ManyToManyField(blank=True, help_text='LLM calls associated with this dataset usage analysis', related_name='dataset_analyses', to='vso_query_builder.llmcall'),
        ),
        migrations.AddField(
            model_name='paperanalysis',
            name='llm_calls',
            field=models.ManyToManyField(blank=True, help_text='LLM calls associated with this paper analysis', related_name='paper_analyses', to='vso_query_builder.llmcall'),
        ),
    ]
