# Generated by Django 5.2.1 on 2025-07-21 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0049_llmcall_datasetusage_llm_calls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='datasource',
        ),
        migrations.RemoveField(
            model_name='observatory',
            name='slug',
        ),
        migrations.AddField(
            model_name='observatory',
            name='datasource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vso_query_builder.datasource'),
        ),
        migrations.AddField(
            model_name='observatory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='observatory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='observatory',
            name='short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='observatory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vso_query_builder.observatory'),
            preserve_default=False,
        ),
    ]
