# Generated by Django 5.2.1 on 2025-07-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0050_remove_instrument_datasource_remove_observatory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observatory',
            name='description',
        ),
    ]
