# Generated by Django 5.2.1 on 2025-07-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0051_remove_observatory_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanonicalDatasetUsage',
        ),
    ]
