# Generated by Django 5.2.1 on 2025-07-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0052_delete_canonicaldatasetusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
