# Generated by Django 5.2.1 on 2025-08-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0053_alter_instrument_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='ads_metadata_fetched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='ads_metadata_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal_abbrev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
