# Generated by Django 5.2.1 on 2025-08-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0054_paper_abstract_paper_ads_metadata_fetched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperanalysis',
            name='configuration_name',
            field=models.CharField(blank=True, help_text='LLM configuration used for this analysis', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paperanalysis',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_query_builder.paper'),
        ),
        migrations.AlterUniqueTogether(
            name='paperanalysis',
            unique_together={('paper', 'configuration_name')},
        ),
    ]
