# Generated by Django 5.2.1 on 2025-10-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0056_datasetusage_configuration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetusage',
            name='paper_analysis',
            field=models.ForeignKey(blank=True, help_text='PaperAnalysis that generated this dataset usage', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_usages', to='vso_query_builder.paperanalysis'),
        ),
        migrations.AlterField(
            model_name='datasetusage',
            name='configuration_name',
            field=models.CharField(blank=True, help_text='LLM configuration used when creating this usage (deprecated - use paper_analysis.configuration_name)', max_length=50, null=True),
        ),
    ]
