# Generated by Django 5.2.1 on 2025-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0058_backfill_datasetusage_paper_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcall',
            name='render_context',
            field=models.JSONField(blank=True, help_text='Template variables used to render this prompt (enables re-testing with different templates)', null=True),
        ),
    ]
