# Generated by Django 5.0.8 on 2026-02-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0060_add_dataset_usage_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='observatory',
            name='display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
