# Generated by Django 5.2.1 on 2026-02-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0061_instrument_display_name_observatory_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, help_text='OpenAI batch ID (e.g., batch_abc123)', max_length=200, null=True, unique=True)),
                ('input_file_id', models.CharField(blank=True, max_length=200, null=True)),
                ('output_file_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_failed', 'Partially Failed')], default='preparing', max_length=20)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('configuration_name', models.CharField(default='standard', max_length=50)),
                ('paper_mapping', models.JSONField(default=dict, help_text='Maps paper IDs to batch custom_ids')),
                ('total_requests', models.IntegerField(default=0)),
                ('completed_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batch Job',
                'verbose_name_plural': 'Batch Jobs',
                'indexes': [models.Index(fields=['status'], name='vso_query_b_status_5d0efd_idx'), models.Index(fields=['created_at'], name='vso_query_b_created_6e04ce_idx')],
            },
        ),
    ]
