# Generated by Django 5.2.1 on 2026-02-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0063_remove_critique_prediction_remove_critique_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedScript',
        ),
    ]
