# Generated by Django 5.2.1 on 2026-02-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0064_delete_generatedscript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstrumentSourceLookup',
        ),
        migrations.AlterModelOptions(
            name='observatory',
            options={'verbose_name_plural': 'Observatories'},
        ),
    ]
