# Generated by Django 5.2.1 on 2026-02-23 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0066_fix_instrument_observatory_fk_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasetusage',
            name='vso_query_b_paper_a_aded33_idx',
        ),
        migrations.AddIndex(
            model_name='datasetusage',
            index=models.Index(fields=['paper_analysis', 'validation_status'], name='vso_query_b_paper_a_2a76f4_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetusage',
            index=models.Index(fields=['paper', 'validated_at'], name='vso_query_b_paper_i_a99e36_idx'),
        ),
        migrations.AddIndex(
            model_name='paperanalysis',
            index=models.Index(fields=['paper', 'created_at'], name='vso_query_b_paper_i_a3f1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='paperanalysis',
            index=models.Index(fields=['configuration_name'], name='vso_query_b_configu_216ccd_idx'),
        ),
    ]
