# Generated by Django 5.2.1 on 2026-02-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0067_add_validation_queue_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='aws_region_name',
            field=models.CharField(blank=True, help_text='AWS region used at submission time (Bedrock only)', max_length=50, null=True),
        ),
    ]
