# Generated by Django 5.2.1 on 2026-02-25 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0073_paperanalysis_pipeline_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_name', models.CharField(help_text='Original instrument name as written in the paper', max_length=255)),
                ('match_level', models.CharField(choices=[('unmatched', 'Unmatched'), ('mission_only', 'Mission Only'), ('instrument_no_time', 'Instrument, No Valid Time'), ('partial', 'Partially Resolved'), ('full', 'Fully Resolved')], db_index=True, help_text='How far grounding succeeded for this instrument mention', max_length=30)),
                ('data_system', models.CharField(blank=True, help_text="Data system slug used for grounding (e.g. 'vso', 'cdaweb')", max_length=50)),
                ('general_comments', models.TextField(blank=True, help_text='General comments about this instrument as extracted from the paper')),
                ('normalized_data', models.JSONField(blank=True, default=dict, help_text='Full instrument entry from normalized_instrument_details JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='pipelinenode',
            new_name='vso_query_b_analysi_4e0c4f_idx',
            old_name='pipenode_analysis_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelinenode',
            new_name='vso_query_b_parent__516d8c_idx',
            old_name='pipenode_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelinenode',
            new_name='vso_query_b_status_30defc_idx',
            old_name='pipenode_status_idx',
        ),
        migrations.AlterField(
            model_name='pipelinenode',
            name='stage',
            field=models.CharField(choices=[('paper_analysis', 'Paper Analysis'), ('structuring', 'Structuring'), ('instrument', 'Instrument'), ('grounding', 'Grounding'), ('grounding_datasystem', 'Grounding Data System'), ('grounding_substep', 'Grounding Substep'), ('grounding_match', 'Grounding Match'), ('normalization', 'Normalization'), ('normalizer', 'Normalizer')], max_length=50),
        ),
        migrations.AddField(
            model_name='instrumentmention',
            name='matched_instrument',
            field=models.ForeignKey(blank=True, help_text='Catalog instrument matched from the paper text (null if not in catalog)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_mentions', to='vso_query_builder.instrument'),
        ),
        migrations.AddField(
            model_name='instrumentmention',
            name='matched_observatory',
            field=models.ForeignKey(blank=True, help_text='Catalog mission matched from the paper text (null if no mission found)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_mentions', to='vso_query_builder.observatory'),
        ),
        migrations.AddField(
            model_name='instrumentmention',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_mentions', to='vso_query_builder.paper'),
        ),
        migrations.AddField(
            model_name='instrumentmention',
            name='paper_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_mentions', to='vso_query_builder.paperanalysis'),
        ),
        migrations.AddIndex(
            model_name='instrumentmention',
            index=models.Index(fields=['paper', 'match_level'], name='vso_query_b_paper_i_31cc93_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumentmention',
            index=models.Index(fields=['matched_observatory', 'match_level'], name='vso_query_b_matched_ea6264_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumentmention',
            index=models.Index(fields=['matched_instrument', 'match_level'], name='vso_query_b_matched_f9ae6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instrumentmention',
            unique_together={('paper_analysis', 'raw_name')},
        ),
    ]
