# Generated by Django 5.2.1 on 2026-02-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0074_add_instrument_mention'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrumentmention',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instrumentmention',
            name='paper_name',
            field=models.CharField(blank=True, help_text='Original instrument name as written in the paper (metadata only)', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='instrumentmention',
            constraint=models.UniqueConstraint(condition=models.Q(('matched_instrument__isnull', False)), fields=('paper_analysis', 'matched_instrument'), name='unique_mention_per_instrument'),
        ),
        migrations.AddConstraint(
            model_name='instrumentmention',
            constraint=models.UniqueConstraint(condition=models.Q(('matched_instrument__isnull', True), ('matched_observatory__isnull', False)), fields=('paper_analysis', 'matched_observatory'), name='unique_mention_per_observatory'),
        ),
        migrations.RemoveField(
            model_name='instrumentmention',
            name='raw_name',
        ),
    ]
