# Generated by Django 5.2.1 on 2026-02-26 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0075_redesign_instrument_mention_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instrumentmention',
            name='vso_query_b_paper_i_31cc93_idx',
        ),
        migrations.RemoveField(
            model_name='instrumentmention',
            name='data_system',
        ),
        migrations.RemoveField(
            model_name='instrumentmention',
            name='general_comments',
        ),
        migrations.RemoveField(
            model_name='instrumentmention',
            name='normalized_data',
        ),
        migrations.RemoveField(
            model_name='instrumentmention',
            name='paper',
        ),
        migrations.AlterField(
            model_name='instrumentmention',
            name='matched_observatory',
            field=models.ForeignKey(blank=True, help_text='Set only for mission_only match level — instrument implies observatory otherwise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_mentions', to='vso_query_builder.observatory'),
        ),
    ]
