# Generated by Django 5.2.1 on 2026-03-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0076_slim_instrument_mention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentmention',
            name='paper_name',
        ),
    ]
