# Generated by Django 5.2.1 on 2026-03-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0078_add_dataset_usage_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetusagevalidation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
