# Generated by Django 5.2.1 on 2026-03-06 15:58

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0079_alter_datasetusagevalidation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True, help_text='Rich scientific noun phrase describing the instrument (~100–200 chars). Primary LLM grounding signal in Stage 3 and source for the embedding vector. Should include instrument type, physical quantity measured, and probe name for multi-spacecraft missions.'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='display_name',
            field=models.CharField(blank=True, help_text='Short label for UI display only. Not used in any pipeline logic.', max_length=200),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='1536-dim pgvector embedding of the description field (text-embedding-3-small). Pre-filters instrument candidates before Stage 3 LLM grounding. Auto-regenerated via post_save when description changes.', null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='full_name',
            field=models.CharField(blank=True, help_text="Short canonical identifier used as a name anchor in Stage 3 LLM grounding prompts (e.g. 'FIELDS/MAG', 'HPCA', 'FGM'). Despite the field name, keep this CONCISE — it should match the abbreviation used in research papers. Maps to instrument_name in grounding catalog entries.", max_length=255),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='short_name',
            field=models.CharField(help_text="External catalog identifier: VSO slug (e.g. 'LASCO') or SPASE URI (e.g. 'spase://SMWG/Instrument/SOHO/LASCO'). Used as instrument_code in grounding catalog entries. NEVER modify after initial import — this is the stable ID that links records to CDAWeb/VSO data systems.", max_length=300),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='datasource',
            field=models.ForeignKey(blank=True, help_text="Data system this observatory belongs to (e.g. 'vso', 'cdaweb').", null=True, on_delete=django.db.models.deletion.CASCADE, to='vso_query_builder.datasource'),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='display_name',
            field=models.CharField(blank=True, help_text='Short label for UI display only. Not used in any pipeline logic.', max_length=200),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='name',
            field=models.CharField(help_text="Mission name used in Stage 1/2 LLM prompts for mission identification. Must be probe-specific for multi-spacecraft constellations — e.g. 'MMS-1' not 'MMS', 'GOES-13' not 'GOES', 'STEREO-A' not 'STEREO'. Managed by the update_instrument_descriptions management command.", max_length=300),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='short_name',
            field=models.CharField(blank=True, help_text="External catalog identifier: VSO slug (e.g. 'SOHO') or SPASE URI (e.g. 'spase://SMWG/Observatory/MMS/1'). Used as mission_code in grounding catalog entries and as the DB lookup key. NEVER modify after initial import.", max_length=300),
        ),
    ]
