# Generated by Django 5.2.1 on 2026-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0080_alter_instrument_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcall',
            name='estimated_cost_usd',
            field=models.DecimalField(decimal_places=6, default=None, help_text='Estimated cost in USD', max_digits=10, null=True),
        ),
    ]
