# Generated by Django 5.2.1 on 2026-03-19 14:51

from django.db import migrations


def backfill_null_costs(apps, schema_editor):
    LLMCall = apps.get_model('vso_query_builder', 'LLMCall')
    updated = LLMCall.objects.filter(
        estimated_cost_usd=0, total_tokens__gt=0
    ).update(estimated_cost_usd=None)
    if updated:
        print(f"\n  Backfilled {updated} LLMCall records: set estimated_cost_usd from 0 to None")


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0081_alter_llmcall_estimated_cost_usd'),
    ]

    operations = [
        migrations.RunPython(backfill_null_costs, migrations.RunPython.noop),
    ]
