# Generated by Django 5.2.1 on 2026-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0083_rename_cadences_key_in_extra_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinenode',
            name='label',
            field=models.TextField(),
        ),
    ]
