# Generated by Django 5.2.1 on 2026-03-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0084_alter_pipelinenode_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatory',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Concise scientific description of the mission/observatory for inclusion in LLM mission-identification prompts. Helps models match paper references to catalog entries (e.g. geographic location for ground stations, science domain for spacecraft). Managed by update_observatory_descriptions command.'),
        ),
    ]
