# Generated by Django 5.2.1 on 2026-04-03 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0085_add_observatory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phenomenon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iri', models.CharField(help_text="HelioKNOW IRI, e.g. 'hkp:SolarWind'", max_length=500, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhenomenonMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_name', models.CharField(help_text='Instrument name as it appears in the structured output', max_length=500)),
                ('period_name', models.CharField(blank=True, help_text='DataCollectionPeriod name from the structured output', max_length=500)),
                ('quote', models.TextField(blank=True, help_text='physobs_quote from the structured output supporting this identification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenomenon_mentions', to='vso_query_builder.paperanalysis')),
                ('phenomenon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='vso_query_builder.phenomenon')),
            ],
            options={
                'indexes': [models.Index(fields=['paper_analysis'], name='vso_query_b_paper_a_685bfa_idx'), models.Index(fields=['phenomenon'], name='vso_query_b_phenome_d663f7_idx')],
            },
        ),
    ]
