# Generated by Django 5.2.1 on 2026-05-15 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0086_add_phenomenon_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenomenonMentionValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.UUIDField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], max_length=20)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phenomenon Mention Validation',
                'verbose_name_plural': 'Phenomenon Mention Validations',
            },
        ),
        migrations.AddField(
            model_name='phenomenonmention',
            name='physical_observable',
            field=models.TextField(blank=True, help_text='Source physical_observable text from the structured instrument data'),
        ),
        migrations.AddField(
            model_name='phenomenonmention',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phenomenonmention',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_phenomenon_mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phenomenonmention',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phenomenonmention',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='phenomenon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phenomenonmention',
            name='instrument_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='phenomenonmention',
            name='period_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='phenomenonmention',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='phenomenonmention',
            index=models.Index(fields=['validation_status'], name='vso_query_b_validat_a738d0_idx'),
        ),
        migrations.AddField(
            model_name='phenomenonmentionvalidation',
            name='phenomenon_mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='vso_query_builder.phenomenonmention'),
        ),
        migrations.AddField(
            model_name='phenomenonmentionvalidation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenomenon_mention_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='phenomenonmentionvalidation',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('phenomenon_mention', 'user'), name='unique_phenom_user_validation'),
        ),
        migrations.AddConstraint(
            model_name='phenomenonmentionvalidation',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('phenomenon_mention', 'anonymous_id'), name='unique_phenom_anon_validation'),
        ),
    ]
