# Generated by Django 5.2.1 on 2026-05-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0087_phenomenonmentionvalidation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenomenonmention',
            name='supporting_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phenomenon_mentions', to='vso_query_builder.supportquote'),
        ),
    ]
