# Generated by Django 5.2.1 on 2026-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0090_phenomenonmention_matched_instrument_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='catalog_source',
            field=models.CharField(choices=[('standard', 'Standard (VSO/CDAWeb import)'), ('custom', 'Custom (authored, e.g. group-level generic)')], db_index=True, default='standard', help_text="Provenance of this row. 'standard' = VSO/CDAWeb import with a real queryable data-system ID. 'custom' = authored row (e.g. a group-level generic instrument); a valid grounding target but NOT a CDAWeb-tagged InstrumentID, so snippet generation skips it and emits a custom marker.", max_length=20),
        ),
    ]
