# Generated by Django 5.2.1 on 2026-06-30 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0091_instrument_catalog_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDownstreamRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('configuration_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('collecting', 'Collecting'), ('batching', 'Batching'), ('committing', 'Committing'), ('completed', 'Completed'), ('failed', 'Failed')], default='preparing', max_length=20)),
                ('aws_region_name', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_ids', models.JSONField(default=list, help_text='Paper IDs (str) in this run')),
                ('current_wave', models.IntegerField(default=0)),
                ('total_papers', models.IntegerField(default=0)),
                ('llm_complete_papers', models.JSONField(default=list, help_text='Paper IDs whose LLM prefix has fully resolved')),
                ('committed_papers', models.JSONField(default=list, help_text='Paper IDs replayed in commit mode (final outputs written)')),
                ('failed_papers', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batch Downstream Run',
                'verbose_name_plural': 'Batch Downstream Runs',
                'indexes': [models.Index(fields=['status'], name='vso_query_b_status_4afd13_idx'), models.Index(fields=['created_at'], name='vso_query_b_created_1c79e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CachedLLMResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_hash', models.CharField(db_index=True, max_length=64)),
                ('call_type', models.CharField(blank=True, default='', max_length=100)),
                ('request_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('batched', 'Batched'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('wave', models.IntegerField(blank=True, null=True)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('finish_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_responses', to='vso_query_builder.batchjob')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_responses', to='vso_query_builder.batchdownstreamrun')),
            ],
            options={
                'verbose_name': 'Cached LLM Response',
                'verbose_name_plural': 'Cached LLM Responses',
                'indexes': [models.Index(fields=['run', 'status'], name='vso_query_b_run_id_181d74_idx'), models.Index(fields=['run', 'request_hash'], name='vso_query_b_run_id_d99abe_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'request_hash'), name='unique_cached_response_per_run')],
            },
        ),
    ]
