# Generated by Django 5.2.1 on 2026-09-22 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0091_deduplicate_and_unique_phenomenon_mention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDownstreamRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('configuration_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('collecting', 'Collecting'), ('batching', 'Batching'), ('committing', 'Committing'), ('completed', 'Completed'), ('failed', 'Failed')], default='preparing', max_length=20)),
                ('aws_region_name', models.CharField(blank=True, max_length=50, null=True)),
                ('corpus_mode', models.BooleanField(default=False)),
                ('paper_ids', models.JSONField(default=list, help_text='Paper IDs (str) in this run (provenance)')),
                ('current_wave', models.IntegerField(default=0)),
                ('total_papers', models.IntegerField(default=0)),
                ('llm_complete_papers', models.JSONField(default=list, help_text='LEGACY (pre-RunPaper runs) — see RunPaper states')),
                ('committed_papers', models.JSONField(default=list, help_text='LEGACY (pre-RunPaper runs) — see RunPaper states')),
                ('failed_papers', models.JSONField(default=list, help_text='LEGACY (pre-RunPaper runs)')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('leased_until', models.DateTimeField(blank=True, null=True)),
                ('lease_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batch Downstream Run',
                'verbose_name_plural': 'Batch Downstream Runs',
            },
        ),
        migrations.CreateModel(
            name='BatchPipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('configuration_name', models.CharField(max_length=50)),
                ('aws_region_name', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_ids', models.JSONField(default=list)),
                ('stage', models.CharField(choices=[('extract', 'Extract text'), ('step1', 'Paper analysis (step 1)'), ('downstream', 'Downstream (wave runner)'), ('analyze', 'Snippet analysis'), ('done', 'Done')], default='extract', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('allow_ocr', models.BooleanField(default=False)),
                ('run_execution', models.BooleanField(default=False)),
                ('corpus_mode', models.BooleanField(default=False)),
                ('extract_dispatched', models.BooleanField(default=False)),
                ('extract_done', models.BooleanField(default=False)),
                ('analyze_dispatched', models.BooleanField(default=False)),
                ('analyze_done', models.BooleanField(default=False)),
                ('leased_until', models.DateTimeField(blank=True, null=True)),
                ('lease_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Batch Pipeline Run',
                'verbose_name_plural': 'Batch Pipeline Runs',
            },
        ),
        migrations.CreateModel(
            name='CachedLLMResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_hash', models.CharField(db_index=True, max_length=64)),
                ('call_type', models.CharField(blank=True, default='', max_length=100)),
                ('request_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('batched', 'Batched'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('wave', models.IntegerField(blank=True, null=True)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('finish_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cached LLM Response',
                'verbose_name_plural': 'Cached LLM Responses',
            },
        ),
        migrations.CreateModel(
            name='RunPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('collecting', 'Collecting'), ('llm_complete', 'LLM complete'), ('committing', 'Committing'), ('committed', 'Committed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Commit attempts')),
                ('error', models.TextField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='When a chunk claimed this row (stale-claim recovery)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Run Paper',
                'verbose_name_plural': 'Run Papers',
            },
        ),
        migrations.RemoveConstraint(
            model_name='phenomenonmention',
            name='unique_phenomenon_mention_per_instrument',
        ),
        migrations.AddField(
            model_name='batchjob',
            name='trigger_downstream',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datasetusagevalidation',
            name='instrument_correct',
            field=models.BooleanField(blank=True, help_text='Whether the instrument of the claim is correct', null=True),
        ),
        migrations.AddField(
            model_name='datasetusagevalidation',
            name='mission_correct',
            field=models.BooleanField(blank=True, help_text='Whether the observatory/mission of the claim is correct', null=True),
        ),
        migrations.AddField(
            model_name='datasetusagevalidation',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('mention_only', 'Mention only'), ('external_summary', "Cites others' work"), ('review_reproduction', 'Reproduced figure'), ('infrastructure', 'Instrument/design paper'), ('theory_context', 'Theory only'), ('other', 'Other (see notes)')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='datasetusagevalidation',
            name='window_correct',
            field=models.BooleanField(blank=True, help_text='Whether the observation window of the claim is correct', null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='catalog_source',
            field=models.CharField(choices=[('standard', 'Standard (VSO/CDAWeb import)'), ('custom', 'Custom (authored, e.g. group-level generic)')], db_index=True, default='standard', help_text="Provenance of this row. 'standard' = VSO/CDAWeb import with a real queryable data-system ID. 'custom' = authored row (e.g. a group-level generic instrument); a valid grounding target but NOT a CDAWeb-tagged InstrumentID, so snippet generation skips it and emits a custom marker.", max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='approved_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='latest_observation_end_all',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='latest_observation_end_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pending_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='usage_stats_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(condition=models.Q(('approved_usage_count__gt', 0)), fields=['-latest_observation_end_approved', 'bibcode'], name='paper_latest_end_appr_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(condition=models.Q(('approved_usage_count__gt', 0), ('pending_usage_count__gt', 0), _connector='OR'), fields=['-latest_observation_end_all', 'bibcode'], name='paper_latest_end_all_idx'),
        ),
        migrations.AddConstraint(
            model_name='phenomenonmention',
            constraint=models.UniqueConstraint(fields=('paper_analysis', 'phenomenon', 'instrument_name', 'period_name'), name='unique_phenomenon_mention_per_period'),
        ),
        migrations.AddIndex(
            model_name='batchdownstreamrun',
            index=models.Index(fields=['status'], name='vso_query_b_status_4afd13_idx'),
        ),
        migrations.AddIndex(
            model_name='batchdownstreamrun',
            index=models.Index(fields=['created_at'], name='vso_query_b_created_1c79e0_idx'),
        ),
        migrations.AddField(
            model_name='batchpipelinerun',
            name='downstream_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vso_query_builder.batchdownstreamrun'),
        ),
        migrations.AddField(
            model_name='batchpipelinerun',
            name='step1_batch_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vso_query_builder.batchjob'),
        ),
        migrations.AddField(
            model_name='cachedllmresponse',
            name='batch_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_responses', to='vso_query_builder.batchjob'),
        ),
        migrations.AddField(
            model_name='cachedllmresponse',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_responses', to='vso_query_builder.batchdownstreamrun'),
        ),
        migrations.AddField(
            model_name='runpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_run_states', to='vso_query_builder.paper'),
        ),
        migrations.AddField(
            model_name='runpaper',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='vso_query_builder.batchdownstreamrun'),
        ),
        migrations.AddIndex(
            model_name='batchpipelinerun',
            index=models.Index(fields=['status'], name='vso_query_b_status_595e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchpipelinerun',
            index=models.Index(fields=['created_at'], name='vso_query_b_created_8ca141_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedllmresponse',
            index=models.Index(fields=['run', 'status'], name='vso_query_b_run_id_181d74_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedllmresponse',
            index=models.Index(fields=['run', 'request_hash'], name='vso_query_b_run_id_d99abe_idx'),
        ),
        migrations.AddConstraint(
            model_name='cachedllmresponse',
            constraint=models.UniqueConstraint(fields=('run', 'request_hash'), name='unique_cached_response_per_run'),
        ),
        migrations.AddIndex(
            model_name='runpaper',
            index=models.Index(fields=['run', 'state'], name='vso_query_b_run_id_8e7d09_idx'),
        ),
        migrations.AddConstraint(
            model_name='runpaper',
            constraint=models.UniqueConstraint(fields=('run', 'paper'), name='uniq_runpaper_run_paper'),
        ),
    ]
