# Generated by Django 5.2.1 on 2026-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0092_batchdownstreamrun_cachedllmresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdownstreamrun',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchdownstreamrun',
            name='lease_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchdownstreamrun',
            name='leased_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
