# Generated by Django 5.2.1 on 2026-07-02 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0093_batchdownstreamrun_last_progress_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='trigger_downstream',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BatchPipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('configuration_name', models.CharField(max_length=50)),
                ('aws_region_name', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_ids', models.JSONField(default=list)),
                ('stage', models.CharField(choices=[('extract', 'Extract text'), ('step1', 'Paper analysis (step 1)'), ('downstream', 'Downstream (wave runner)'), ('analyze', 'Snippet analysis'), ('done', 'Done')], default='extract', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('allow_ocr', models.BooleanField(default=False)),
                ('run_execution', models.BooleanField(default=False)),
                ('extract_dispatched', models.BooleanField(default=False)),
                ('extract_done', models.BooleanField(default=False)),
                ('analyze_dispatched', models.BooleanField(default=False)),
                ('analyze_done', models.BooleanField(default=False)),
                ('leased_until', models.DateTimeField(blank=True, null=True)),
                ('lease_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('downstream_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vso_query_builder.batchdownstreamrun')),
                ('step1_batch_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vso_query_builder.batchjob')),
            ],
            options={
                'verbose_name': 'Batch Pipeline Run',
                'verbose_name_plural': 'Batch Pipeline Runs',
                'indexes': [models.Index(fields=['status'], name='vso_query_b_status_595e9b_idx'), models.Index(fields=['created_at'], name='vso_query_b_created_8ca141_idx')],
            },
        ),
    ]
