# Generated by Django 5.2.1 on 2026-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0094_batchjob_trigger_downstream_batchpipelinerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedllmresponse',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
