# Generated by Django 5.2.1 on 2026-07-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0095_cachedllmresponse_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdownstreamrun',
            name='committed_papers',
            field=models.JSONField(default=list, help_text='LEGACY (pre-RunPaper runs) — see RunPaper states'),
        ),
        migrations.AlterField(
            model_name='batchdownstreamrun',
            name='failed_papers',
            field=models.JSONField(default=list, help_text='LEGACY (pre-RunPaper runs)'),
        ),
        migrations.AlterField(
            model_name='batchdownstreamrun',
            name='llm_complete_papers',
            field=models.JSONField(default=list, help_text='LEGACY (pre-RunPaper runs) — see RunPaper states'),
        ),
        migrations.AlterField(
            model_name='batchdownstreamrun',
            name='paper_ids',
            field=models.JSONField(default=list, help_text='Paper IDs (str) in this run (provenance)'),
        ),
        migrations.CreateModel(
            name='RunPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('collecting', 'Collecting'), ('llm_complete', 'LLM complete'), ('committing', 'Committing'), ('committed', 'Committed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Commit attempts')),
                ('error', models.TextField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='When a chunk claimed this row (stale-claim recovery)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_run_states', to='vso_query_builder.paper')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='vso_query_builder.batchdownstreamrun')),
            ],
            options={
                'verbose_name': 'Run Paper',
                'verbose_name_plural': 'Run Papers',
                'indexes': [models.Index(fields=['run', 'state'], name='vso_query_b_run_id_8e7d09_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'paper'), name='uniq_runpaper_run_paper')],
            },
        ),
    ]
