# Generated by Django 5.2.1 on 2026-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0096_alter_batchdownstreamrun_committed_papers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdownstreamrun',
            name='corpus_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchpipelinerun',
            name='corpus_mode',
            field=models.BooleanField(default=False),
        ),
    ]
