# Generated by Django 5.2.1 on 2026-07-21 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0097_batchdownstreamrun_corpus_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='approved_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='latest_observation_end_all',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='latest_observation_end_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='pending_usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='usage_stats_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(condition=models.Q(('approved_usage_count__gt', 0)), fields=['-latest_observation_end_approved', 'bibcode'], name='paper_latest_end_appr_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(condition=models.Q(('approved_usage_count__gt', 0), ('pending_usage_count__gt', 0), _connector='OR'), fields=['-latest_observation_end_all', 'bibcode'], name='paper_latest_end_all_idx'),
        ),
    ]
