# Generated by Django 5.2.1 on 2026-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0099_backfill_paper_usage_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetusagevalidation',
            name='instrument_correct',
            field=models.BooleanField(blank=True, help_text='Whether the instrument of the claim is correct', null=True),
        ),
        migrations.AddField(
            model_name='datasetusagevalidation',
            name='mission_correct',
            field=models.BooleanField(blank=True, help_text='Whether the observatory/mission of the claim is correct', null=True),
        ),
        migrations.AddField(
            model_name='datasetusagevalidation',
            name='window_correct',
            field=models.BooleanField(blank=True, help_text='Whether the observation window of the claim is correct', null=True),
        ),
    ]
