# Generated by Django 5.2.1 on 2026-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0100_datasetusagevalidation_instrument_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetusagevalidation',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('mention_only', 'Mention/background only'), ('external_summary', "Cites others' analysis"), ('review_reproduction', 'Reproduced figure from cited work'), ('infrastructure', 'Instrument/infrastructure paper'), ('theory_context', 'Theory only'), ('composite_component', 'Composite-product component'), ('other', 'Other (see notes)')], max_length=32, null=True),
        ),
    ]
