# Generated by Django 5.2.1 on 2026-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vso_query_builder', '0101_datasetusagevalidation_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetusagevalidation',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('mention_only', 'Mention only'), ('external_summary', "Cites others' work"), ('review_reproduction', 'Reproduced figure'), ('infrastructure', 'Instrument/design paper'), ('theory_context', 'Theory only'), ('other', 'Other (see notes)')], max_length=32, null=True),
        ),
    ]
