#!/bin/bash
# Refresh AWS credentials from SSO session and update .env file
# Works with both local dev and production environments

set -e

PROFILE="${AWS_PROFILE:-bedrock}"
ENV_FILE=".env"

echo "🔐 Refreshing AWS credentials from SSO profile: $PROFILE"

# Check if SSO session is active
if ! aws sts get-caller-identity --profile "$PROFILE" &>/dev/null; then
    echo "❌ SSO session expired or not logged in"
    echo "Please run: aws sso login --profile $PROFILE"
    exit 1
fi

echo "✅ SSO session active"

# Export credentials (returns JSON format)
CREDS=$(aws configure export-credentials --profile "$PROFILE")

if [ -z "$CREDS" ]; then
    echo "❌ Failed to export credentials"
    exit 1
fi

# Parse JSON credentials using python3
AWS_ACCESS_KEY_ID=$(echo "$CREDS" | python3 -c "import sys, json; print(json.load(sys.stdin)['AccessKeyId'])")
AWS_SECRET_ACCESS_KEY=$(echo "$CREDS" | python3 -c "import sys, json; print(json.load(sys.stdin)['SecretAccessKey'])")
AWS_SESSION_TOKEN=$(echo "$CREDS" | python3 -c "import sys, json; print(json.load(sys.stdin)['SessionToken'])")
AWS_EXPIRATION=$(echo "$CREDS" | python3 -c "import sys, json; print(json.load(sys.stdin)['Expiration'])")

# Update .env file
# Remove old AWS credentials
sed -i.bak '/^AWS_ACCESS_KEY_ID=/d' "$ENV_FILE" 2>/dev/null || true
sed -i.bak '/^AWS_SECRET_ACCESS_KEY=/d' "$ENV_FILE" 2>/dev/null || true
sed -i.bak '/^AWS_SESSION_TOKEN=/d' "$ENV_FILE" 2>/dev/null || true
sed -i.bak '/^AWS_DEFAULT_REGION=/d' "$ENV_FILE" 2>/dev/null || true
sed -i.bak '/^AWS_PROFILE=/d' "$ENV_FILE" 2>/dev/null || true

# Clean up backup file
rm -f "${ENV_FILE}.bak"

# Append new credentials
cat >> "$ENV_FILE" <<EOF

# AWS Credentials (auto-generated by refresh-aws-credentials.sh)
# Last updated: $(date)
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
AWS_DEFAULT_REGION=us-west-2
EOF

echo "✅ Credentials written to $ENV_FILE"
echo "⏰ Valid until: $AWS_EXPIRATION"
echo ""
echo "Next steps:"
echo "  docker compose restart api celery"
